### ISSUE TITLE
Error when assigning `nil` to an Array type

### ISSUE THREAD

**Issue by caioeps** [davydovanton/shallow_attributes#22]
Hi! I'm facing an issue when assigning a `nil` value to an Array type attribute.

Context:

```ruby
class User
  include ShallowAttributes
  attribute :arr, Array, of: Integer, default: []
end

user = User.new arr: nil
#=> ShallowAttributes::Type::InvalidValueError: Invalid value "" for type "Array"
```

However, when not passing `arr` it works as expected.

```ruby
user = User.new
#=> #<User arr=[]>
```

Is this the expected behaviour? I can create a PR if you want to, I'm needing this :)

**Comment by davydovanton** [comment]
hey, I think raising error for `arr: nil` is expected behaviour. What do you want to see here?

**Comment by caioeps** [comment]
I was expecting to build an object with an empty array instead. Something like this:

```ruby
user = User.new arr: nil
#=> #<User arr=[]>
```

**Comment by davydovanton** [comment]
okay, but `nil` is not `Array` type. In this case you need to use `Null | Array` type 🤔

**Comment by caioeps** [comment]
Oh, I see. In this case I'll have to implement my own Array type. I was actually wondering if it wasn't supposed to use the default value if passing `nil` as argument. Thanks for taking your time to answer me! Great gem, though :)
