### ISSUE TITLE
Update documentation for base class functionality

### ISSUE THREAD

**Issue by davydovanton** [davydovanton/shallow_attributes#8]
We need to update our documentation for this case https://github.com/davydovanton/shallow_attributes/pull/7/files#diff-aa8cb646f17ea5eb573d32dbcc6a9b86R25.
That is all 👍

**Comment by tatey** [comment]
I'm happy to put my hand up to write this. I actually enjoy writing documentation. You have already written a really nice README 😄

Do you see this going in https://github.com/davydovanton/shallow_attributes#using-shallowattributes-with-classes, or does it get its own section?

**Comment by davydovanton** [comment]
@tatey I think `Using ShallowAttributes with Classes` section will be okay 👍
